import * as THREE from 'three';
import { exteriorMaterial, roofMaterial, frameMaterial } from './materialSystem.js';
import { deriveRoofConstruction, deriveCeilingSystems, deriveFoundationSchedule } from './phase10Systems.js';

const mat=(color,opacity=1)=>new THREE.MeshStandardMaterial({color,transparent:opacity<1,opacity,roughness:.75});
function box(g,size,pos,material,data={}){const m=new THREE.Mesh(new THREE.BoxGeometry(...size),material);m.position.set(...pos);m.castShadow=true;m.receiveShadow=true;Object.assign(m.userData,data,{phase:10});g.add(m);return m;}
function tube(g,pts,r,color,data={}){if(pts.length<2)return;const curve=new THREE.CatmullRomCurve3(pts.map(p=>new THREE.Vector3(p[0],p[1],p[2])));const m=new THREE.Mesh(new THREE.TubeGeometry(curve,Math.max(8,pts.length*4),r,8,false),mat(color,.85));Object.assign(m.userData,data,{group:'mep',phase:10});g.add(m);}

export function buildAdvancedFoundationGroup(building){const g=new THREE.Group();g.name='phase10_foundations';g.userData.group='structure';const concrete=exteriorMaterial('concrete','#77756f');for(const f of deriveFoundationSchedule(building)){const host=findHost(building,f.host);if(f.type==='strip'&&host){const len=Math.hypot(host.end[0]-host.start[0],host.end[1]-host.start[1]);const p=[(host.start[0]+host.end[0])/2,-.3,(host.start[1]+host.end[1])/2];const m=box(g,[len,f.depth,f.width],p,concrete,{group:'structure',foundationId:f.id,hostId:f.host});m.rotation.y=Math.atan2(host.end[0]-host.start[0],host.end[1]-host.start[1]);}else if(f.type==='pad'){box(g,[f.width,f.thickness,f.depth],[(host?.position?.[0]||0),f.elevation,(host?.position?.[2]||0)],concrete,{group:'structure',foundationId:f.id,hostId:f.host});}}return g;}
function findHost(building,id){for(const l of building.levels||[]){const w=(l.walls||[]).find(x=>x.id===id);if(w)return w;const c=(l.components||[]).find(x=>x.id===id);if(c)return c;}return null;}

export function buildAdvancedRoofGroup(building){const g=new THREE.Group();g.name='phase10_roof_construction';g.userData.group='roof';const top=building.levels?.at(-1);if(!top)return g;const planes=deriveRoofConstruction(building);const base=top.elevation+top.height;for(const p of planes){if(p.polygon.length<3)continue;const shape=new THREE.Shape();p.polygon.forEach(([x,z],i)=>i?shape.lineTo(x,z):shape.moveTo(x,z));shape.closePath();const geo=new THREE.ShapeGeometry(shape);geo.rotateX(-Math.PI/2);const mesh=new THREE.Mesh(geo,roofMaterial(building.roof.material,building.roof.color));mesh.position.y=base;mesh.userData={group:'roof',roofPlaneId:p.id,roofType:p.type,phase:10};mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);}const d=building.roof.details||{};if(d.gutters){const b=top.footprint||[];for(let i=0;i<b.length;i++){const a=b[i],c=b[(i+1)%b.length];const len=Math.hypot(c[0]-a[0],c[1]-a[1]);const m=box(g,[len,.08,.08],[(a[0]+c[0])/2,base-.03,(a[1]+c[1])/2],frameMaterial('aluminium'),{group:'roof',roofDetail:'gutter'});m.rotation.y=Math.atan2(c[0]-a[0],c[1]-a[1]);}}return g;}

export function buildAdvancedCeilingGroup(building){const g=new THREE.Group();g.name='phase10_ceilings';g.userData.group='interior';const systems=deriveCeilingSystems(building);for(const c of systems){const room=findRoom(building,c.roomId);if(!room)continue;const pts=room.polygon||[];if(pts.length<3)continue;const xs=pts.map(p=>p[0]),zs=pts.map(p=>p[1]);const minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs);const slab=box(g,[maxX-minX-.04,.035,maxZ-minZ-.04],[(minX+maxX)/2,c.elevation,(minZ+maxZ)/2],mat(0xe7e5df),{group:'interior',ceilingId:c.id,room:room.name});for(let x=minX+c.gridSpacing;x<maxX-.05;x+=c.gridSpacing){const l=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(x,c.elevation+.025,minZ),new THREE.Vector3(x,c.elevation+.025,maxZ)]),new THREE.LineBasicMaterial({color:0x9ca3aa}));l.userData={group:'interior',ceilingId:c.id};g.add(l);}for(let z=minZ+c.gridSpacing;z<maxZ-.05;z+=c.gridSpacing){const l=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(minX,c.elevation+.026,z),new THREE.Vector3(maxX,c.elevation+.026,z)]),new THREE.LineBasicMaterial({color:0x9ca3aa}));l.userData={group:'interior',ceilingId:c.id};g.add(l);}}return g;}
function findRoom(building,id){for(const l of building.levels||[]){const r=(l.rooms||[]).find(x=>x.id===id);if(r)return r;}return null;}

export function buildStructuralGridGroup(building){const g=new THREE.Group();g.name='phase10_structural_grid';g.userData.group='structure';const grid=building.structural?.grid;if(!grid)return g;const top=building.levels?.[0];const z0=Math.min(...(top?.footprint||[[0,0]]).map(p=>p[1])),z1=Math.max(...(top?.footprint||[[0,0]]).map(p=>p[1]));const x0=Math.min(...(top?.footprint||[[0,0]]).map(p=>p[0])),x1=Math.max(...(top?.footprint||[[0,0]]).map(p=>p[0]));for(const x of grid.x||[]){const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(x,.01,z0),new THREE.Vector3(x,.01,z1)]),new THREE.LineBasicMaterial({color:0x8b6f47,transparent:true,opacity:.45}));line.userData={group:'structure',gridAxis:'X',gridValue:x};g.add(line);}for(const z of grid.z||[]){const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(x0,.012,z),new THREE.Vector3(x1,.012,z)]),new THREE.LineBasicMaterial({color:0x8b6f47,transparent:true,opacity:.45}));line.userData={group:'structure',gridAxis:'Z',gridValue:z};g.add(line);}return g;}

export function buildDetailedMepGroup(building){const g=new THREE.Group();g.name='phase10_mep_routes';g.userData.group='mep';const specs={electrical:[.018,0xf3c74f],plumbing:[.035,0x3d9be9],drainage:[.045,0x6d6f78],hvac:[.04,0x63c5c8],fire:[.025,0xe45d5d]};for(const [name,[r,c]] of Object.entries(specs)){for(const route of building.systems?.[name]?.routes||[]){tube(g,route.points||[],r,c,{discipline:name,routeId:route.id,type:route.type});}}return g;}

export function phase10GeometryReport(building){return {roofPlanes:building.roof?.planes?.length||0,foundations:building.structural?.foundations?.length||0,ceilings:building.ceilingSystems?.length||0,structuralGridX:building.structural?.grid?.x?.length||0,structuralGridZ:building.structural?.grid?.z?.length||0,mepRoutes:Object.values(building.systems||{}).reduce((n,s)=>n+(s.routes||[]).length,0)};}
