// Phase 31 — Professional Revision & Change Tracking
export const PHASE31_SCHEMA = 'archvision-bim-1.21';
const clone=v=>JSON.parse(JSON.stringify(v));
const now=()=>new Date().toISOString();
function ids(building){const out=[]; for(const l of building.levels||[]){for(const w of l.walls||[])out.push({id:w.id,type:'wall',level:l.index}); for(const r of l.rooms||[])out.push({id:r.id,type:'room',level:l.index}); for(const w of l.walls||[])for(const o of w.openings||[])out.push({id:o.id,type:'opening',level:l.index}); for(const c of l.components||[])out.push({id:c.id,type:'component',level:l.index});} return out.filter(x=>x.id);}
export function normalizePhase31(building){building.metadata ||= {}; building.phase31 ||= {}; const p=building.phase31; p.schema=PHASE31_SCHEMA; p.revision ||= 1; p.label ||= 'Revision 1'; p.history ||= []; p.baseline ||= null; p.lastChangeSet ||= null; p.updatedAt ||= null; building.metadata.schema=PHASE31_SCHEMA; return building;}
export function phase31Fingerprint(building){const b=clone(building); delete b.phase31; delete b.metadata?.updatedAt; return JSON.stringify(b);}
export function capturePhase31Baseline(building,{label}={}){normalizePhase31(building); const p=building.phase31; p.baseline={revision:p.revision,label:label||p.label,fingerprint:phase31Fingerprint(building),elements:ids(building),capturedAt:now()}; p.updatedAt=now(); return clone(p.baseline);}
export function comparePhase31(building,previous){normalizePhase31(building); const before=previous?.baseline?.elements||ids(previous||{}); const after=ids(building); const key=x=>`${x.type}:${x.id}`; const a=new Map(before.map(x=>[key(x),x])), b=new Map(after.map(x=>[key(x),x])); const added=after.filter(x=>!a.has(key(x))), removed=before.filter(x=>!b.has(key(x))); const common=after.filter(x=>a.has(key(x))); return {schema:PHASE31_SCHEMA,added,removed,unchanged:common,counts:{added:added.length,removed:removed.length,unchanged:common.length},changed:added.length+removed.length>0};}
export function createPhase31Revision(building,{label,author='architect',note=''}={}){normalizePhase31(building); const p=building.phase31; const previous=p.baseline?clone(p):null; const changeSet=comparePhase31(building,previous||{}); p.revision=Number(p.revision||0)+1; p.label=label||`Revision ${p.revision}`; p.history.push({revision:p.revision,label:p.label,author,note,changeSet,capturedAt:now()}); p.lastChangeSet=changeSet; p.baseline={revision:p.revision,label:p.label,fingerprint:phase31Fingerprint(building),elements:ids(building),capturedAt:now()}; p.updatedAt=now(); return clone(p.history.at(-1));}
export function validatePhase31(building){normalizePhase31(building); const p=building.phase31,errors=[],warnings=[]; if(p.schema!==PHASE31_SCHEMA)errors.push('Phase 31 schema mismatch.'); if(!Number.isInteger(p.revision)||p.revision<1)errors.push('Invalid Phase 31 revision number.'); if(!Array.isArray(p.history))errors.push('Revision history is missing.'); if(!p.baseline)warnings.push('No revision baseline has been captured.'); return {valid:errors.length===0,errors,warnings};}
export function phase31Manifest(building){normalizePhase31(building); const p=building.phase31; return {schema:PHASE31_SCHEMA,revision:p.revision,label:p.label,history:clone(p.history),lastChangeSet:clone(p.lastChangeSet),baseline:clone(p.baseline),updatedAt:p.updatedAt};}
