// Phase 24 — roof, stair and structural topology. This is model-derived
// coordination data: it describes architectural intent and connections;
// it is not structural engineering or code certification.
export const PHASE24_SCHEMA = 'archvision-bim-1.14';
const clone = v => JSON.parse(JSON.stringify(v));
const now = () => new Date().toISOString();
const dist = (a,b) => Math.hypot((a?.[0]||0)-(b?.[0]||0),(a?.[1]||0)-(b?.[1]||0));
const wallLen = w => dist(w.start,w.end);
function footprintBounds(pts=[]){const xs=pts.map(p=>p[0]),zs=pts.map(p=>p[1]);return {minX:Math.min(...xs),maxX:Math.max(...xs),minZ:Math.min(...zs),maxZ:Math.max(...zs)};}
function roofTopology(top, roof={}){
  const fp=top?.footprint||[]; if(fp.length<3)return {type:roof.type||'flat',planes:[],edges:[],ridge:[],valleys:[],openings:[]};
  const b=footprintBounds(fp), pitch=Number(roof.pitchDeg||22), overhang=Number(roof.overhang||0.5), type=roof.type||'hip';
  const edges=fp.map((p,i)=>({id:`roof-edge-${top.index}-${i+1}`,from:p,to:fp[(i+1)%fp.length],length:dist(p,fp[(i+1)%fp.length]),role:'eave'}));
  const planes=[];
  if(type==='flat'||type==='parapet') planes.push({id:`roof-plane-${top.index}-1`,slopeDeg:0,area:(b.maxX-b.minX+2*overhang)*(b.maxZ-b.minZ+2*overhang),role:'flat'});
  else if(type==='gable') { planes.push({id:`roof-plane-${top.index}-L`,slopeDeg:pitch,role:'gable-slope',edges:edges.slice(0,2).map(e=>e.id)}); planes.push({id:`roof-plane-${top.index}-R`,slopeDeg:pitch,role:'gable-slope',edges:edges.slice(2).map(e=>e.id)}); }
  else if(type==='mono') planes.push({id:`roof-plane-${top.index}-1`,slopeDeg:pitch,role:'mono-slope',edges:edges.map(e=>e.id)});
  else for(let i=0;i<Math.max(4,edges.length);i++) planes.push({id:`roof-plane-${top.index}-${i+1}`,slopeDeg:pitch,role:'hip-slope',edgeId:edges[i%edges.length].id});
  const cx=(b.minX+b.maxX)/2,cz=(b.minZ+b.maxZ)/2;
  const ridge = type==='hip' ? [{id:`ridge-${top.index}-1`,from:[b.minX+(b.maxX-b.minX)*0.325,cz],to:[b.maxX-(b.maxX-b.minX)*0.325,cz],elevationOffset:Math.max(.6,Math.min(b.maxX-b.minX,b.maxZ-b.minZ)/2*Math.tan(pitch*Math.PI/180))}] : type==='gable' ? [{id:`ridge-${top.index}-1`,from:[b.minX+overhang,cz],to:[b.maxX-overhang,cz],elevationOffset:Math.max(.6,(b.maxZ-b.minZ)/2*Math.tan(pitch*Math.PI/180))}] : [];
  const valleys = type==='hip' && fp.length>4 ? fp.slice(0,Math.floor(fp.length/2)).map((p,i)=>({id:`valley-${top.index}-${i+1}`,from:p,to:[cx,cz],role:'valley'})) : [];
  return {type,pitchDeg:pitch,overhang,footprint:clone(fp),edges,planes,ridge,valleys,openings:clone(roof.openings||[]),topLevel:top.index};
}
function stairTopology(building, stair){const from=building.levels?.find(l=>l.index===stair.fromFloor),to=building.levels?.find(l=>l.index===stair.toFloor);if(!from||!to)return null;const rise=Math.max(0,to.elevation-from.elevation),width=Number(stair.width||1.1),risers=Math.max(1,Math.ceil(rise/(Number(stair.maxRiser||.18)))),riser=rise/risers,tread=Number(stair.treadDepth||.28),run=risers*tread,landing=Number(stair.landingDepth||width),flights=stair.type==='straight'?1:2;return {id:stair.id,fromFloor:stair.fromFloor,toFloor:stair.toFloor,type:stair.type||'straight',width,risers,riserHeight:Number(riser.toFixed(4)),treadDepth:tread,run:Number(run.toFixed(3)),flights,landings:flights>1?[{depth:landing,width,elevation:from.elevation+riser*Math.ceil(risers/2)}]:[],opening:{id:`stair-opening-${stair.id}`,width:width+.2,length:run+(flights>1?landing:0),fromFloor:stair.fromFloor,toFloor:stair.toFloor,headroomHeight:2.1},headroom:{clearHeight:2.1,required:true,checked:false},spaceLinks:[]};}
function structuralTopology(building){const nodes=[],connections=[],elements=[];for(const level of building.levels||[]){for(const w of level.walls||[]){const ends=[w.start,w.end];ends.forEach((p,i)=>{const id=`SN-${level.index}-${w.id}-${i}`;if(!nodes.some(n=>n.id===id))nodes.push({id,level:level.index,position:p,type:'support-node',sourceWall:w.id});});elements.push({id:`SB-${level.index}-${w.id}`,type:'ring-beam',level:level.index,wallId:w.id,length:wallLen(w),start:w.start,end:w.end});}}
  const byLevel=new Map();nodes.forEach(n=>{const a=byLevel.get(n.level)||[];a.push(n);byLevel.set(n.level,a);});
  for(const [level,ns] of byLevel)for(let i=0;i<ns.length;i++)for(let j=i+1;j<ns.length;j++){if(dist(ns[i].position,ns[j].position)<8)connections.push({id:`SC-${level}-${i}-${j}`,type:'beam-to-node',level,from:ns[i].id,to:ns[j].id});}
  const columns=[];for(const n of nodes){if(n.level===building.levels?.[0]?.index)columns.push({id:`COL-${n.id}`,nodeId:n.id,position:n.position,fromLevel:n.level,toLevel:building.levels?.at(-1)?.index||n.level});}
  return {nodes,elements,connections:connections.slice(0,Math.max(0,nodes.length*3)),columns,foundations:columns.map(c=>({id:`FND-${c.id}`,columnId:c.id,type:'pad-footing',level:building.levels?.[0]?.index||1}))};}
export function normalizePhase24(building){building.metadata ||= {};building.metadata.schema=PHASE24_SCHEMA;building.phase24 ||= {};building.phase24.schema=PHASE24_SCHEMA;building.phase24.roof ||= {};building.phase24.stairs ||= [];building.phase24.structure ||= {nodes:[],elements:[],connections:[],columns:[],foundations:[]};building.phase24.updatedAt ||= null;return building;}
export function regeneratePhase24(building,reason='phase24-regeneration'){normalizePhase24(building);const top=building.levels?.at(-1);building.phase24.roof=roofTopology(top,building.roof||{});building.phase24.stairs=(building.stairs||[]).map(s=>stairTopology(building,s)).filter(Boolean);building.phase24.structure=structuralTopology(building);building.phase24.roof.stairOpenings=building.phase24.stairs.map(s=>s.opening);building.phase24.updatedAt=now();building.phase24.reason=reason;building.phase24.associative={roofPlanes:building.phase24.roof.planes.length,ridgeMembers:building.phase24.roof.ridge.length,valleys:building.phase24.roof.valleys.length,stairOpenings:building.phase24.stairs.length,structuralNodes:building.phase24.structure.nodes.length,structuralConnections:building.phase24.structure.connections.length};return building;}
export function phase24Manifest(building){normalizePhase24(building);return {schema:PHASE24_SCHEMA,project:{id:building.id,name:building.name},roof:clone(building.phase24.roof),stairs:clone(building.phase24.stairs),structure:clone(building.phase24.structure),associative:clone(building.phase24.associative||{}),notes:['Phase 24 derives roof, stair and structural topology for BIM coordination.','Structural relationships are design-intent coordination data and are not a substitute for engineering analysis.']};}
export function validatePhase24(building){normalizePhase24(building);const errors=[],warnings=[],p=building.phase24;if(!p.updatedAt)warnings.push('Phase 24 topology has not been regenerated.');if(!p.roof?.planes?.length)warnings.push('No roof planes were derived.');for(const s of p.stairs||[]){if(s.risers<1)errors.push(`Stair ${s.id} has no risers.`);if(s.riserHeight<=0||s.riserHeight>.25)warnings.push(`Stair ${s.id} riser ${s.riserHeight} m should be reviewed.`);if(!s.opening?.id)errors.push(`Stair ${s.id} has no stair opening relationship.`);}for(const c of p.structure?.connections||[])if(c.from===c.to)errors.push(`Structural connection ${c.id} connects a node to itself.`);if((p.structure?.nodes||[]).length===0)warnings.push('No structural topology nodes were derived.');return {valid:errors.length===0,errors,warnings};}
