import * as THREE from 'three';
const COLORS={electrical:0xf3c74f,plumbing:0x3d9be9,hvac:0x63c5c8,fire:0xe45d5d};
function material(color,opacity=.9){return new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.05,transparent:opacity<1,opacity});}
function cylinderBetween(a,b,r,mat,meta){const va=new THREE.Vector3(...a),vb=new THREE.Vector3(...b),d=vb.clone().sub(va),len=d.length()||.01;const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,len,12),mat);m.position.copy(va.clone().add(vb).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());m.castShadow=true;m.receiveShadow=true;m.userData={group:'mep',discipline:meta.discipline,phase25:true,...meta};return m;}
function ductBetween(a,b,size,mat,meta){const va=new THREE.Vector3(...a),vb=new THREE.Vector3(...b),d=vb.clone().sub(va),len=d.length()||.01;const m=new THREE.Mesh(new THREE.BoxGeometry(size,size,len),mat);m.position.copy(va.clone().add(vb).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),d.normalize());m.castShadow=true;m.receiveShadow=true;m.userData={group:'mep',discipline:meta.discipline,phase25:true,...meta};return m;}
function marker(p,color,meta){const m=new THREE.Mesh(new THREE.SphereGeometry(.07,12,8),new THREE.MeshStandardMaterial({color}));m.position.set(...p);m.userData={group:'mep',phase25:true,...meta};return m;}
export function buildPhase25MepGroup(building){const root=new THREE.Group();root.name='phase25_connected_mep';root.userData={group:'mep',discipline:'mep',phase25:true};for(const r of building.phase25?.routes||[]){const mat=material(COLORS[r.discipline]||0xffffff,.86);for(let i=1;i<r.points.length;i++){const a=r.points[i-1],b=r.points[i];const m=r.shape==='duct'?ductBetween(a,b,r.diameter||.16,mat,{discipline:r.discipline,routeId:r.id,system:r.system}):cylinderBetween(a,b,Math.max(.012,(r.diameter||.025)/2),mat,{discipline:r.discipline,routeId:r.id,system:r.system});root.add(m);}}
  for(const f of building.phase25?.fittings||[]){const c=COLORS[f.discipline]||0xffffff;root.add(marker(f.position,c,{fittingId:f.id,type:f.type,discipline:f.discipline}));}
  for(const e of building.phase25?.equipment||[]){const c=COLORS[e.type?.startsWith('smoke')?'fire':e.type?.startsWith('hvac')||e.type==='diffuser'?'hvac':e.type?.startsWith('plumbing')?'plumbing':'electrical'];root.add(marker(e.position,c,{equipmentId:e.id,type:e.type,discipline:e.type?.startsWith('smoke')?'fire':e.type?.startsWith('hvac')||e.type==='diffuser'?'hvac':e.type?.startsWith('plumbing')?'plumbing':'electrical'}));}
  for(const p of building.phase25?.penetrations||[])root.add(marker(p.position,0xff9a3d,{penetrationId:p.id,type:p.type,discipline:'mep'}));
  return root;}
