// Phase 12 construction geometry — layered wall skins, roof framing, stair guards and MEP fittings.
import * as THREE from 'three';
import { deriveWallLayerGeometry, deriveRoofFraming, deriveStairConstruction, deriveMepFittings } from './phase12Systems.js';

const mats={render:new THREE.MeshStandardMaterial({color:0xd8d2c6,roughness:.85}),masonry:new THREE.MeshStandardMaterial({color:0xb6a99a,roughness:.9}),'mineral-wool':new THREE.MeshStandardMaterial({color:0xd7c9a9,roughness:1}),plaster:new THREE.MeshStandardMaterial({color:0xe8e4dc,roughness:.9}),'gypsum-stud':new THREE.MeshStandardMaterial({color:0xd5d9dc,roughness:.85}),tile:new THREE.MeshStandardMaterial({color:0xc9c5bb,roughness:.8}),concrete:new THREE.MeshStandardMaterial({color:0x8c8a84,roughness:.9}),metal:new THREE.MeshStandardMaterial({color:0x70777d,metalness:.65,roughness:.35}),plywood:new THREE.MeshStandardMaterial({color:0x9b7554,roughness:.8}),plasterboard:new THREE.MeshStandardMaterial({color:0xe4e0d7,roughness:.9})};
const materialFor=k=>mats[k]||mats.plaster;
function layerMesh(g,l){const len=Math.hypot(l.end[0]-l.start[0],l.end[1]-l.start[1]);const m=new THREE.Mesh(new THREE.BoxGeometry(Math.max(.01,len),l.height,Math.max(.008,l.thickness)),materialFor(l.material));m.position.set((l.start[0]+l.end[0])/2,l.baseElevation+l.height/2,(l.start[1]+l.end[1])/2);m.rotation.y=Math.atan2(l.end[0]-l.start[0],l.end[1]-l.start[1]);m.userData={group:'structure',phase:12,wallId:l.wallId,layer:l.name,material:l.material};m.castShadow=true;m.receiveShadow=true;g.add(m);}
function cylinderBetween(a,b,r,mat){const v=new THREE.Vector3().subVectors(b,a);const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,v.length,8),mat);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.normalize());return m;}
export function buildPhase12ConstructionGroup(building){const g=new THREE.Group();g.name='phase12_construction';g.userData.group='structure';for(const l of deriveWallLayerGeometry(building))layerMesh(g,l);
 const roof=new THREE.Group();roof.name='roof_framing';roof.userData.group='roof';for(const r of deriveRoofFraming(building)){const a=new THREE.Vector3(...r.start),b=new THREE.Vector3(...r.end);const m=cylinderBetween(a,b,.045,mats.metal);m.userData={group:'roof',phase:12,framingId:r.id,framingType:r.type};roof.add(m);}g.add(roof);
 const stairs=new THREE.Group();stairs.name='stair_guards';stairs.userData.group='structure';for(const s of deriveStairConstruction(building)){const stair=building.stairs.find(x=>x.id===s.id);const p=stair?.position||[0,0];const from=building.levels.find(l=>l.index===s.fromFloor);if(!from)continue;const run=s.run;const rail=cylinderBetween(new THREE.Vector3(p[0],from.elevation+.95,p[1]),new THREE.Vector3(p[0]+Math.min(run,4),from.elevation+(s.risers*s.riserHeight)+.95,p[1]),.025,mats.metal);rail.userData={group:'structure',phase:12,stairId:s.id,detail:'handrail'};stairs.add(rail);const guard=cylinderBetween(new THREE.Vector3(p[0],from.elevation,p[1]),new THREE.Vector3(p[0],from.elevation+s.guardHeight,p[1]),.02,mats.metal);guard.userData={group:'structure',phase:12,stairId:s.id,detail:'guardrail'};stairs.add(guard);}g.add(stairs);
 const fittings=new THREE.Group();fittings.name='mep_fittings';fittings.userData.group='mep';for(const f of deriveMepFittings(building)){if(!f.position||f.position.length<3)continue;const m=new THREE.Mesh(new THREE.SphereGeometry(.07,8,8),new THREE.MeshStandardMaterial({color:f.discipline==='electrical'?0xe4b94f:f.discipline==='plumbing'?0x3f8bd6:f.discipline==='hvac'?0x55b9bd:0xd65a5a}));m.position.set(f.position[0],f.position[1],f.position[2]);m.userData={group:'mep',phase:12,fittingId:f.id,discipline:f.discipline,type:f.type};fittings.add(m);}g.add(fittings);return g;}
