// Phase 34 — Professional Construction Schedules & Coordination Package
export const PHASE34_SCHEMA = 'archvision-bim-1.24';
const clone=v=>JSON.parse(JSON.stringify(v)); const now=()=>new Date().toISOString();
function openingRows(b){const rows=[]; for(const l of b.levels||[])for(const w of l.walls||[])for(const o of w.openings||[])rows.push({id:o.id||`${w.id}-opening`,hostWall:w.id,level:l.index,type:o.type||'opening',width:Number(o.width||0),height:Number(o.height||0),sill:Number(o.sillHeight||0)}); return rows;}
function roomRows(b){const rows=[]; for(const l of b.levels||[])for(const r of l.rooms||[])rows.push({id:r.id,level:l.index,name:r.name||r.id,areaM2:Number(area(r.polygon).toFixed(2)),floorFinish:r.floorFinish||'unspecified',ceilingFinish:r.ceilingFinish||'unspecified'}); return rows;}
function area(p){let s=0; for(let i=0;i<(p||[]).length;i++){const a=p[i],b=p[(i+1)%p.length]; s+=a[0]*b[1]-b[0]*a[1];} return Math.abs(s)/2;}
function dimensions(b){return (b.levels||[]).flatMap(l=>(l.walls||[]).map(w=>({id:w.id,level:l.index,lengthM:Number(Math.hypot(w.end[0]-w.start[0],w.end[1]-w.start[1]).toFixed(3)),thicknessM:Number((w.thickness||0).toFixed(3)),heightM:Number((w.height||0).toFixed(3))})));}
export function normalizePhase34(building){building.metadata ||= {}; building.phase34 ||= {}; const p=building.phase34; p.schema=PHASE34_SCHEMA; p.schedules ||= {}; p.coordination ||= {}; p.updatedAt ||= null; building.metadata.schema=PHASE34_SCHEMA; return building;}
export function generatePhase34Package(building){normalizePhase34(building); const p=building.phase34; p.schedules={walls:dimensions(building),openings:openingRows(building),rooms:roomRows(building)}; p.coordination={qaReady:building.phase32?.deliverables?.some(d=>d.id==='qa-report'&&d.status==='ready')??false,revisionReady:Boolean(building.phase31?.baseline),exportReady:Boolean(building.phase33?.exports?.length),checks:['wall-dimensions','opening-hosts','room-finishes','revision-reference','export-reference']}; p.status=Object.values(p.coordination).filter(v=>typeof v==='boolean').every(Boolean)?'ready':'review'; p.updatedAt=now(); return clone(p);}
export function validatePhase34(building){normalizePhase34(building); const p=building.phase34,errors=[],warnings=[]; if(p.schema!==PHASE34_SCHEMA)errors.push('Phase 34 schema mismatch.'); for(const key of ['walls','openings','rooms'])if(!Array.isArray(p.schedules?.[key]))errors.push(`Missing ${key} schedule.`); if(!p.coordination)errors.push('Coordination package is missing.'); if(p.status!=='ready')warnings.push('Construction package requires prerequisite coordination review.'); return {valid:errors.length===0,errors,warnings};}
export function phase34Manifest(building){normalizePhase34(building); return clone(building.phase34);}
