// Phase 37 — Final Model Hardening & Deterministic Integrity
export const PHASE37_SCHEMA='archvision-bim-1.27';
const clone=v=>JSON.parse(JSON.stringify(v));
const now=()=>new Date().toISOString();
const stable=v=>{if(Array.isArray(v))return '['+v.map(stable).join(',')+']';if(v&&typeof v==='object')return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}';return JSON.stringify(v);};
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');}
export function normalizePhase37(building){building.metadata||={};building.phase37||={};const p=building.phase37;p.schema=PHASE37_SCHEMA;p.integrity||={};p.checks||={};p.updatedAt||=null;building.metadata.schema=PHASE37_SCHEMA;return building;}
export function generatePhase37Integrity(building){normalizePhase37(building);const p=building.phase37;const source=clone(building);delete source.phase37;const serialized=stable(source);const counts={levels:building.levels?.length||0,walls:(building.levels||[]).reduce((n,l)=>n+(l.walls?.length||0),0),rooms:(building.levels||[]).reduce((n,l)=>n+(l.rooms?.length||0),0),openings:(building.levels||[]).reduce((n,l)=>n+(l.walls||[]).reduce((m,w)=>m+(w.openings?.length||0),0),0)};p.integrity={algorithm:'fnv1a-32',hash:hash(serialized),canonicalLength:serialized.length,counts};p.checks={schema:Boolean(building.metadata?.schema),phase36:Boolean(building.phase36?.release?.ready),nonEmpty:Boolean(counts.levels&&counts.walls),uniqueIds:uniqueIds(building)};p.ready=Object.values(p.checks).every(Boolean);p.status=p.ready?'hardened':'review';p.updatedAt=now();return clone(p);}
function uniqueIds(building){const ids=[];for(const l of building.levels||[]){for(const w of l.walls||[]){ids.push(w.id);for(const o of w.openings||[])ids.push(o.id);}for(const r of l.rooms||[])ids.push(r.id);}return ids.filter(Boolean).length===new Set(ids.filter(Boolean)).size;}
export function validatePhase37(building){normalizePhase37(building);const p=building.phase37,errors=[],warnings=[];if(p.schema!==PHASE37_SCHEMA)errors.push('Phase 37 schema mismatch.');if(!p.integrity?.hash)errors.push('Integrity fingerprint is missing.');if(!p.checks?.uniqueIds)errors.push('Duplicate model identifiers detected.');if(!p.checks?.phase36)warnings.push('Phase 36 release gate is not ready.');if(!p.ready)warnings.push('Final hardening requires review.');return {valid:errors.length===0,errors,warnings,ready:Boolean(p.ready)};}
export function phase37Manifest(building){normalizePhase37(building);return clone(building.phase37);}
