// Phase 33 — Professional Interoperability & Export Manifest
export const PHASE33_SCHEMA = 'archvision-bim-1.23';
const clone=v=>JSON.parse(JSON.stringify(v));
const now=()=>new Date().toISOString();
const collect=(b)=>{const out=[]; for(const l of b.levels||[]){for(const w of l.walls||[])out.push({id:w.id,type:'IfcWall',level:l.index}); for(const r of l.rooms||[])out.push({id:r.id,type:'IfcSpace',level:l.index}); for(const w of l.walls||[])for(const o of w.openings||[])out.push({id:o.id,type:o.type||'IfcOpeningElement',level:l.index}); for(const c of l.components||[])out.push({id:c.id,type:c.type||'IfcBuildingElementProxy',level:l.index});} return out.filter(x=>x.id);};
export function normalizePhase33(building){building.metadata ||= {}; building.phase33 ||= {}; const p=building.phase33; p.schema=PHASE33_SCHEMA; p.targetFormats ||= ['ifc4','json']; p.units ||= building.units||'metric'; p.coordinates ||= {system:'local-building',origin:[0,0,0]}; p.entities ||= []; p.exports ||= []; p.updatedAt ||= null; building.metadata.schema=PHASE33_SCHEMA; return building;}
export function generatePhase33ExportManifest(building,{author='ArchVision',projectName}={}){normalizePhase33(building); const p=building.phase33; p.entities=collect(building); p.project={name:projectName||building.name||building.id||'ArchVision Project',author,discipline:'Architecture',schema:PHASE33_SCHEMA}; p.exports=p.targetFormats.map(format=>({format,status:'ready',entityCount:p.entities.length,generatedAt:now()})); p.updatedAt=now(); return clone(p);}
export function validatePhase33(building){normalizePhase33(building); const p=building.phase33,errors=[],warnings=[]; if(p.schema!==PHASE33_SCHEMA)errors.push('Phase 33 schema mismatch.'); if(!Array.isArray(p.entities)||p.entities.length<1)warnings.push('No exportable architectural entities were found.'); if(!Array.isArray(p.exports)||p.exports.length<1)errors.push('Export manifest is missing.'); if(!p.project?.name)errors.push('Export project identity is missing.'); return {valid:errors.length===0,errors,warnings};}
export function phase33Manifest(building){normalizePhase33(building); return clone(building.phase33);}
