// Phase 25 — connected MEP authoring and coordination.
// This layer turns design-intent MEP locations into connected, model-derived
// routes, fittings, risers, equipment references and deterministic coordination
// findings. It is not a substitute for engineering design or code certification.
export const PHASE25_SCHEMA = 'archvision-bim-1.15';
const clone = v => JSON.parse(JSON.stringify(v));
const now = () => new Date().toISOString();
const dist = (a,b) => Math.hypot((a?.[0]||0)-(b?.[0]||0),(a?.[1]||0)-(b?.[1]||0));
const center = room => { const p=room?.polygon||[]; if(!p.length)return [0,0]; const s=p.reduce((a,v)=>[a[0]+v[0],a[1]+v[1]],[0,0]); return [s[0]/p.length,s[1]/p.length]; };
const wet = r => /bath|toilet|kitchen|laundry|utility/i.test(`${r?.name||''} ${r?.type||''}`);
const occupied = r => !/garage|store|plant|utility/i.test(`${r?.name||''} ${r?.type||''}`);
function pointSeg(p,a,b){const dx=b[0]-a[0],dz=b[1]-a[1],l2=dx*dx+dz*dz||1;const t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dz)/l2));const q=[a[0]+t*dx,a[1]+t*dz];return {t,point:q,distance:dist(p,q)};}
function segIntersect(a,b,c,d){const den=(b[0]-a[0])*(d[1]-c[1])-(b[1]-a[1])*(d[0]-c[0]);if(Math.abs(den)<1e-9)return null;const t=((c[0]-a[0])*(d[1]-c[1])-(c[1]-a[1])*(d[0]-c[0]))/den;const u=((c[0]-a[0])*(b[1]-a[1])-(c[1]-a[1])*(b[0]-a[0]))/den;if(t>=0&&t<=1&&u>=0&&u<=1)return [a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])];return null;}
function path(a,b,via){return via?[a,via,b]:[a,b];}
function addRoute(routes, id, networkId, discipline, system, floor, points, y, diameter, shape='pipe'){let safe=points||[];if(safe.length>=2&&safe.slice(1).reduce((s,p,i)=>s+dist(safe[i],p),0)<0.001){safe=[safe[0],[safe[0][0]+0.10,safe[0][1]],safe[1]];}const length=safe.slice(1).reduce((s,p,i)=>s+dist(safe[i],p),0);routes.push({id,networkId,discipline,system,floor,shape,diameter:Number(diameter||0.025),points:safe.map(p=>[Number(p[0].toFixed(4)),Number(y.toFixed(3)),Number(p[1].toFixed(4))]),lengthM:Number(length.toFixed(3)),connectivity:{start:networkId,end:networkId}});}
function addRoute3D(routes,id,networkId,discipline,system,floor,points,diameter,shape='pipe'){let safe=points||[];const length=safe.slice(1).reduce((sum,p,i)=>sum+Math.hypot((p[0]||0)-(safe[i][0]||0),(p[1]||0)-(safe[i][1]||0),(p[2]||0)-(safe[i][2]||0)),0);routes.push({id,networkId,discipline,system,floor,shape,diameter:Number(diameter||0.025),points:safe.map(p=>p.map(v=>Number(v.toFixed(4)))),lengthM:Number(length.toFixed(3)),connectivity:{start:networkId,end:networkId},vertical:true});}
function addNetwork(networks,n){networks.push(n);return n;}
function buildElectrical(building, networks, routes, fittings, equipment){
  const panels=[]; const first=building.levels?.[0];
  const panelRoom=(first?.rooms||[]).find(r=>/foyer|hall|corridor|utility|plant/i.test(r.name||'')) || first?.rooms?.[0];
  if(panelRoom){const p=center(panelRoom);const panel={id:'DB-01',type:'distribution-board',floor:first.index,position:[p[0]-0.45,first.elevation+1.35,p[1]],circuits:[]};panels.push(panel);equipment.push(panel);}
  const panel=panels[0]; if(!panel)return panels;
  const riserId='ER-01'; const top=building.levels?.at(-1); addNetwork(networks,{id:riserId,discipline:'electrical',system:'riser',level:first.index,type:'vertical-riser',source:panel.id,status:'connected'});
  if(top)addRoute3D(routes,'EL-RISER-01',riserId,'electrical','riser',first.index,[[panel.position[0],panel.position[1],panel.position[2]],[panel.position[0],top.elevation+0.35,panel.position[2]]],0.025,'conduit');
  let circuitNo=1;
  for(const level of building.levels||[]){for(const room of (level.rooms||[]).filter(occupied)){const c=center(room);const nid=`EL-C${circuitNo++}`;addNetwork(networks,{id:nid,discipline:'electrical',system:'lighting',level:level.index,type:'circuit',source:level.index===first.index?panel.id:riserId,roomId:room.id,status:'connected'});const source=level.index===first.index?[panel.position[0],panel.position[2]]:[panel.position[0],panel.position[2]];const sourceY=level.index===first.index?panel.position[1]:level.elevation+1.20;addRoute(routes,`EL-R-${level.index}-${room.id}`,nid,'electrical','lighting',level.index,path(source,c),sourceY,0.018,'conduit');equipment.push({id:`EL-L-${level.index}-${room.id}`,type:'light',floor:level.index,roomId:room.id,position:[c[0],level.elevation+level.height-0.10,c[1]]});const outlet=[c[0]+0.45,c[1]];equipment.push({id:`EL-O-${level.index}-${room.id}`,type:'socket',floor:level.index,roomId:room.id,position:[outlet[0],level.elevation+0.30,outlet[1]]});}}
  return panels;
}
function buildPlumbing(building, networks, routes, fittings, equipment, risers){
  const wetRooms=[];for(const level of building.levels||[])for(const room of level.rooms||[])if(wet(room))wetRooms.push({level,room});
  if(!wetRooms.length)return;
  const base=wetRooms[0],bc=center(base.room); const supplyRiser={id:'PR-01',type:'plumbing-supply-riser',position:[bc[0],bc[1]],fromLevel:building.levels[0]?.index,toLevel:building.levels.at(-1)?.index}; const drainRiser={id:'DR-01',type:'soil-drain-riser',position:[bc[0]+0.12,bc[1]],fromLevel:building.levels[0]?.index,toLevel:building.levels.at(-1)?.index}; risers.push(supplyRiser,drainRiser); const top=building.levels.at(-1); if(top){addNetwork(networks,{id:'PL-RISER-S',discipline:'plumbing',system:'cold-water',level:building.levels[0]?.index,type:'vertical-riser',source:supplyRiser.id,status:'connected'});addNetwork(networks,{id:'PL-RISER-D',discipline:'plumbing',system:'soil-waste',level:building.levels[0]?.index,type:'vertical-riser',source:drainRiser.id,status:'connected'});addRoute3D(routes,'PL-RISER-S','PL-RISER-S','plumbing','cold-water',building.levels[0]?.index,[[bc[0],building.levels[0]?.elevation+0.1,bc[1]],[bc[0],top.elevation+0.25,bc[1]]],0.025,'pipe');addRoute3D(routes,'PL-RISER-D','PL-RISER-D','plumbing','soil-waste',building.levels[0]?.index,[[bc[0]+0.12,building.levels[0]?.elevation+0.1,bc[1]],[bc[0]+0.12,top.elevation+0.25,bc[1]]],0.05,'pipe');}
  let n=1;for(const {level,room} of wetRooms){const c=center(room);const supply=`PL-S${n}`,drain=`PL-D${n}`;addNetwork(networks,{id:supply,discipline:'plumbing',system:'cold-water',level:level.index,type:'supply',source:supplyRiser.id,roomId:room.id,status:'connected'});addNetwork(networks,{id:drain,discipline:'plumbing',system:'soil-waste',level:level.index,type:'drain',source:drainRiser.id,roomId:room.id,status:'connected'});addRoute(routes,`PL-RS-${n}`,supply,'plumbing','cold-water',level.index,path([bc[0],bc[1]],c),level.elevation+0.55,0.025,'pipe');addRoute(routes,`PL-RD-${n}`,drain,'plumbing','soil-waste',level.index,path([bc[0]+0.12,bc[1]], [c[0]+0.15,c[1]]),level.elevation+0.20,0.05,'pipe');equipment.push({id:`PL-F-${n}`,type:'plumbing-fixture',floor:level.index,roomId:room.id,fixtureClass:/toilet/i.test(room.name||'')?'WC':'fixture-group',position:[c[0],level.elevation+0.45,c[1]]});n++;}
}
function buildHvac(building, networks, routes, fittings, equipment){
  let n=1;for(const level of building.levels||[]){const rooms=(level.rooms||[]).filter(occupied);if(!rooms.length)continue;const hub=rooms.find(r=>/corridor|hall|lounge|living/i.test(r.name||''))||rooms[0];const hc=center(hub);const hubId=`HV-H-${level.index}`;equipment.push({id:hubId,type:'hvac-air-handler',floor:level.index,roomId:hub.id,position:[hc[0],level.elevation+level.height-0.35,hc[1]]});for(const room of rooms){const c=center(room);const id=`HV-${n++}`;addNetwork(networks,{id,discipline:'hvac',system:'supply-air',level:level.index,type:'branch',source:hubId,roomId:room.id,status:'connected'});addRoute(routes,`HV-R-${id}`,id,'hvac','supply-air',level.index,path(hc,c),level.elevation+level.height-0.28,0.16,'duct');equipment.push({id:`HV-D-${id}`,type:'diffuser',floor:level.index,roomId:room.id,position:[c[0],level.elevation+level.height-0.25,c[1]]});}}
}
function buildFire(building, networks, routes, equipment){let n=1;for(const level of building.levels||[])for(const room of level.rooms||[]){const c=center(room);const id=`F-${n++}`;addNetwork(networks,{id,discipline:'fire',system:'detection',level:level.index,type:'device',roomId:room.id,status:'standalone'});equipment.push({id:`SM-${id}`,type:'smoke-detector',floor:level.index,roomId:room.id,position:[c[0],level.elevation+level.height-0.12,c[1]]});}}
function deriveFittings(routes){const fittings=[];for(const r of routes){for(let i=1;i<r.points.length-1;i++){const p=r.points[i];fittings.push({id:`FIT-${r.id}-${i}`,type:'elbow',discipline:r.discipline,system:r.system,routeId:r.id,position:p});}}const groups=new Map();for(const r of routes){const k=r.points[0].map(v=>v.toFixed(2)).join(',');const a=groups.get(k)||[];a.push(r);groups.set(k,a);}for(const [k,rs] of groups)if(rs.length>2)fittings.push({id:`TEE-${fittings.length+1}`,type:'tee',discipline:rs[0].discipline,system:rs[0].system,routeIds:rs.map(r=>r.id),position:k.split(',').map(Number)});return fittings;}
function derivePenetrations(building,routes,risers){const out=[];for(const r of routes){for(let i=1;i<r.points.length;i++){const a=[r.points[i-1][0],r.points[i-1][2]],b=[r.points[i][0],r.points[i][2]];const level=building.levels?.find(l=>l.index===r.floor);for(const w of level?.walls||[]){const hit=segIntersect(a,b,w.start,w.end);if(hit){out.push({id:`PEN-${r.id}-${out.length+1}`,routeId:r.id,wallId:w.id,floor:r.floor,position:[hit[0],r.points[i][1],hit[1]],type:'wall-penetration',diameter:r.diameter,required:true});}}}}
  for(const r of risers){for(const level of building.levels||[])out.push({id:`PEN-${r.id}-F${level.index}`,riserId:r.id,floor:level.index,position:[r.position[0],level.elevation,r.position[1]],type:'slab-penetration',required:true});}return out;}
function deriveClashes(building,routes,penetrations){const findings=[];for(const r of routes){for(let i=1;i<r.points.length;i++){const a=[r.points[i-1][0],r.points[i-1][2]],b=[r.points[i][0],r.points[i][2]];const level=building.levels?.find(l=>l.index===r.floor);for(const w of level?.walls||[]){const hit=segIntersect(a,b,w.start,w.end);if(hit&&!penetrations.some(p=>p.routeId===r.id&&p.wallId===w.id))findings.push({id:`CL-${r.id}-${w.id}`,severity:'high',type:'route-wall-conflict',routeId:r.id,wallId:w.id,floor:r.floor,position:[hit[0],r.points[i][1],hit[1]],status:'unresolved'});}}}
  // A route crossing a wall is a required penetration, not automatically a clash.
  return findings;}
export function normalizePhase25(building){building.metadata ||= {};building.metadata.schema=PHASE25_SCHEMA;building.phase25 ||= {};const p=building.phase25;p.schema=PHASE25_SCHEMA;p.networks ||= [];p.routes ||= [];p.fittings ||= [];p.risers ||= [];p.penetrations ||= [];p.equipment ||= [];p.clashes ||= [];p.operations ||= 0;p.updatedAt ||= null;p.associative ||= {};return building;}
export function regeneratePhase25(building,reason='phase25-mep-regeneration'){normalizePhase25(building);const p=building.phase25;p.networks=[];p.routes=[];p.fittings=[];p.risers=[];p.penetrations=[];p.equipment=[];p.clashes=[];buildElectrical(building,p.networks,p.routes,p.fittings,p.equipment);buildPlumbing(building,p.networks,p.routes,p.fittings,p.equipment,p.risers);buildHvac(building,p.networks,p.routes,p.fittings,p.equipment);buildFire(building,p.networks,p.routes,p.fittings,p.equipment);p.fittings=deriveFittings(p.routes);p.penetrations=derivePenetrations(building,p.routes,p.risers);p.clashes=deriveClashes(building,p.routes,p.penetrations);p.operations++;p.updatedAt=now();p.reason=reason;p.associative={networks:p.networks.length,routes:p.routes.length,fittings:p.fittings.length,risers:p.risers.length,penetrations:p.penetrations.length,equipment:p.equipment.length,clashes:p.clashes.length,connectedNetworks:p.networks.filter(n=>n.status==='connected').length};return building;}
export function phase25Manifest(building){normalizePhase25(building);return {schema:PHASE25_SCHEMA,project:{id:building.id,name:building.name},mep:clone(building.phase25),notes:['Phase 25 derives connected MEP coordination data from the canonical Building IR.','Electrical, plumbing, HVAC and fire data are design-intent coordination outputs and require qualified engineering/code review.']};}
export function validatePhase25(building){normalizePhase25(building);const p=building.phase25,errors=[],warnings=[];if(!p.updatedAt)warnings.push('Phase 25 MEP model has not been regenerated.');for(const n of p.networks||[]){if(!n.id)errors.push('MEP network without an id.');if(n.status==='connected'&&!n.source)warnings.push(`Network ${n.id} is connected but has no source reference.`);}for(const r of p.routes||[]){if(!r.points||r.points.length<2)errors.push(`Route ${r.id} has fewer than two points.`);if(!(r.lengthM>0))warnings.push(`Route ${r.id} has zero length.`);if(!['electrical','plumbing','hvac','fire'].includes(r.discipline))errors.push(`Route ${r.id} has invalid discipline.`);}for(const c of p.clashes||[])warnings.push(`Unresolved MEP coordination clash ${c.id}.`);for(const pen of p.penetrations||[])if(!pen.position)errors.push(`Penetration ${pen.id} has no position.`);return {valid:errors.length===0,errors,warnings};}
