import * as THREE from 'three';
import { wallLength } from './buildingModel.js';
import { exteriorMaterial, frameMaterial } from './materialSystem.js';
const concrete=exteriorMaterial('concrete','#9a9892'), foundation=exteriorMaterial('concrete','#77746e'), steel=frameMaterial('aluminium','#5f6870');
function box(g,s,p,r,m,d={}){const x=new THREE.Mesh(new THREE.BoxGeometry(...s),m);x.position.set(...p);x.rotation.y=r;x.castShadow=true;x.receiveShadow=true;Object.assign(x.userData,{group:'structure',...d});g.add(x)}
function pts(level){const a=[],seen=new Set();for(const w of level?.walls||[])for(const p of [w.start,w.end]){const k=`${Math.round(p[0]*100)},${Math.round(p[1]*100)}`;if(!seen.has(k)){seen.add(k);a.push(p)}}return a}
export function buildStructuralGroup(b){const g=new THREE.Group();g.name='structural_system';g.userData.group='structure';const ground=b.levels?.[0];if(!ground)return g;
for(const w of ground.walls||[]){if(!['exterior','compound'].includes(w.type))continue;const len=wallLength(w);if(len<.1)continue;const mx=(w.start[0]+w.end[0])/2,mz=(w.start[1]+w.end[1])/2,r=Math.atan2(w.end[0]-w.start[0],w.end[1]-w.start[1]);box(g,[len+.16,.35,Math.max(w.thickness+.2,.45)],[mx,-.175,mz],r,foundation,{structuralType:'strip-foundation',wallId:w.id,floor:1})}
for(const [x,z] of pts(ground)){for(const l of b.levels||[])box(g,[.3,l.height,.3],[x,l.elevation+l.height/2,z],0,concrete,{structuralType:'column',floor:l.index});box(g,[.75,.25,.75],[x,.05,z],0,foundation,{structuralType:'pad-footing',floor:1})}
for(const l of b.levels||[])for(const w of l.walls||[]){const len=wallLength(w);if(len<.2)continue;const mx=(w.start[0]+w.end[0])/2,mz=(w.start[1]+w.end[1])/2,r=Math.atan2(w.end[0]-w.start[0],w.end[1]-w.start[1]);box(g,[len,.25,Math.max(.2,w.thickness*.9)],[mx,l.elevation+l.height-.15,mz],r,concrete,{structuralType:'ring-beam',wallId:w.id,floor:l.index})}
const top=b.levels?.at(-1);if(top?.footprint?.length){const xs=top.footprint.map(p=>p[0]),zs=top.footprint.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),w=maxX-minX,d=maxZ-minZ,y=top.elevation+top.height+.15;if(w>0&&d>0){box(g,[w*.55,.12,.12],[(minX+maxX)/2,y+Math.max(.3,d*.18),(minZ+maxZ)/2],0,steel,{structuralType:'roof-ridge',floor:top.index});const n=Math.max(2,Math.ceil(w/2.5));for(let i=0;i<=n;i++)box(g,[.08,.08,d],[minX+w*i/n,y,(minZ+maxZ)/2],0,steel,{structuralType:'roof-purlin',floor:top.index})}}
return g}
export function structuralSummary(b){const ls=b.levels||[],walls=ls.flatMap(l=>l.walls||[]).filter(w=>w.type==='exterior'||w.type==='compound'),points=new Set(walls.flatMap(w=>[w.start,w.end]).map(p=>`${Math.round(p[0]*100)/100},${Math.round(p[1]*100)/100}`));return{exteriorWallRuns:walls.length,derivedColumns:points.size*ls.length,storeys:ls.length,foundationType:'RC strip + pad footings',frame:'reinforced-concrete frame'}}
