// Phase 23 — advanced space topology: intersections, T-junctions, multi-room
// plans, circulation, vertical links and topology diagnostics.
export const PHASE23_SCHEMA = 'archvision-bim-1.13';
const EPS = 1e-6;
const NODE_TOL = 0.06;
const clone = v => JSON.parse(JSON.stringify(v));
const now = () => new Date().toISOString();
const dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
const area=pts=>Math.abs(pts.reduce((s,p,i)=>{const q=pts[(i+1)%pts.length];return s+p[0]*q[1]-q[0]*p[1]},0))/2;
const signedArea=pts=>pts.reduce((s,p,i)=>{const q=pts[(i+1)%pts.length];return s+p[0]*q[1]-q[0]*p[1]},0)/2;
const centroid=pts=>{let a=0,cx=0,cy=0;for(let i=0;i<pts.length;i++){const p=pts[i],q=pts[(i+1)%pts.length],f=p[0]*q[1]-q[0]*p[1];a+=f;cx+=(p[0]+q[0])*f;cy+=(p[1]+q[1])*f;}if(Math.abs(a)<EPS)return pts.reduce((s,p)=>[s[0]+p[0]/pts.length,s[1]+p[1]/pts.length],[0,0]);return[cx/(3*a),cy/(3*a)];};
const pointInPoly=(p,pts)=>{let inside=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const a=pts[i],b=pts[j],hit=((a[1]>p[1])!==(b[1]>p[1]))&&(p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1]+1e-12)+a[0]);if(hit)inside=!inside;}return inside;};
const key=p=>`${Math.round(p[0]/NODE_TOL)}:${Math.round(p[1]/NODE_TOL)}`;
function segmentIntersection(a,b,c,d){const r=[b[0]-a[0],b[1]-a[1]],s=[d[0]-c[0],d[1]-c[1]];const cross=(u,v)=>u[0]*v[1]-u[1]*v[0];const den=cross(r,s);if(Math.abs(den)<EPS)return null;const q=[c[0]-a[0],c[1]-a[1]];const t=cross(q,s)/den,u=cross(q,r)/den;if(t>EPS&&t<1-EPS&&u>EPS&&u<1-EPS)return {t,u,point:[a[0]+r[0]*t,a[1]+r[1]*t]};return null;}
function splitWallSegments(walls){
  const params=new Map(walls.map(w=>[w.id,[0,1]]));
  for(let i=0;i<walls.length;i++)for(let j=i+1;j<walls.length;j++){const a=walls[i],b=walls[j],hit=segmentIntersection(a.start,a.end,b.start,b.end);if(hit){params.get(a.id).push(hit.t);params.get(b.id).push(hit.u);}}
  const out=[];
  for(const w of walls){const ts=[...new Set(params.get(w.id).sort((a,b)=>a-b))];for(let i=0;i<ts.length-1;i++){const t0=ts[i],t1=ts[i+1];const p0=[w.start[0]+(w.end[0]-w.start[0])*t0,w.start[1]+(w.end[1]-w.start[1])*t0];const p1=[w.start[0]+(w.end[0]-w.start[0])*t1,w.start[1]+(w.end[1]-w.start[1])*t1];if(dist(p0,p1)>NODE_TOL/4)out.push({id:`${w.id}:s${i+1}`,wallId:w.id,start:p0,end:p1,t0,t1});}}
  return out;
}
export function buildArrangement23(walls){
  const segs=splitWallSegments(walls),vertices=new Map(),edges=[];
  const vertex=p=>{const k=key(p);if(!vertices.has(k))vertices.set(k,{key:k,p:[p[0],p[1]],out:[]});return vertices.get(k)};
  for(const s of segs){const a=vertex(s.start),b=vertex(s.end);const e={id:`${s.id}:ab`,segmentId:s.id,wallId:s.wallId,from:a,to:b,used:false};const r={id:`${s.id}:ba`,segmentId:s.id,wallId:s.wallId,from:b,to:a,used:false};e.rev=r;r.rev=e;a.out.push(e);b.out.push(r);edges.push(e,r);}
  const angle=(a,b)=>Math.atan2(b.p[1]-a.p[1],b.p[0]-a.p[0]);
  for(const v of vertices.values())v.out.sort((a,b)=>angle(a.from,a.to)-angle(b.from,b.to));
  const faces=[];
  for(const start of edges){if(start.used)continue;let e=start,pts=[],wallIds=[],guard=0;while(e&&!e.used&&guard++<edges.length+4){e.used=true;pts.push(e.from.p);wallIds.push(e.wallId);const outs=e.to.out,ri=outs.indexOf(e.rev);e=outs[(ri+1)%outs.length];if(e===start)break;}if(e===start&&pts.length>=3){const sa=signedArea(pts);if(sa>0.25)faces.push({polygon:pts,wallIds:[...new Set(wallIds)],area:sa});}}
  return {faces,segs,vertices:[...vertices.values()].map(v=>v.p)};
}
function openingPoint(w,o){const len=dist(w.start,w.end)||1;const t=Math.max(0,Math.min(1,(Number(o.offsetAlongWall)||len/2)/len));return[w.start[0]+(w.end[0]-w.start[0])*t,w.start[1]+(w.end[1]-w.start[1])*t];}
function findSpaceAt(level,p){return (level.rooms||[]).find(r=>pointInPoly(p,r.polygon||[]))||null;}
export function normalizePhase23(building){building.metadata ||= {};building.metadata.schema=PHASE23_SCHEMA;building.phase23 ||= {};building.phase23.schema=PHASE23_SCHEMA;building.phase23.spaceTopology ||= {rooms:[],adjacency:[],verticalLinks:[],wallOwnership:[],intersections:[],operations:0,lastRegenerated:null};return building;}
export function regenerateSpaces23(building,{preserveNames=true}={}){
  normalizePhase23(building);const globalRooms=[],adj=[],vertical=[];
  for(const level of building.levels||[]){const old=level.rooms||[],arr=buildArrangement(level.walls||[]);const faces=arr.faces.filter(f=>f.area>=0.75),used=new Set(),next=[];
    for(const f of faces){const c=centroid(f.polygon);let match=null,best=Infinity;if(preserveNames)for(const r of old){if(used.has(r.id)||!r.polygon?.length)continue;const d=dist(c,centroid(r.polygon));if(pointInPoly(c,r.polygon)||d<best){best=d;match=r;}}if(match)used.add(match.id);const id=match?.id||`space-${level.index}-${next.length+1}`;const room={...(match?clone(match):{id,name:`Room ${next.length+1}`,type:'generic'}),id,floor:level.index,polygon:f.polygon.map(p=>p.map(v=>Number(v.toFixed(4)))),areaM2:Number(f.area.toFixed(3)),centroid:centroid(f.polygon).map(v=>Number(v.toFixed(3))),boundaryWallIds:f.wallIds,spaceType:'interior',topologySource:'phase23-planar-arrangement',topologyUpdatedAt:now(),ceilingRelation:{roomId:id,boundary:clone(f.polygon),updatePolicy:'follow-space-boundary'},slabRelation:{roomId:id,boundary:clone(f.polygon),updatePolicy:'follow-space-boundary'}};next.push(room);globalRooms.push({level:level.index,id,areaM2:room.areaM2,wallIds:f.wallIds,centroid:room.centroid});}
    level.rooms=next;const ownership=[];for(const r of next)for(const w of r.boundaryWallIds||[])ownership.push({wallId:w,level:level.index,roomId:r.id});
    for(const w of level.walls||[])for(const o of w.openings||[]){const p=openingPoint(w,o),dx=w.end[0]-w.start[0],dy=w.end[1]-w.start[1],len=Math.hypot(dx,dy)||1,n=[-dy/len,dx/len],eps=0.08,a=findSpaceAt(level,[p[0]+n[0]*eps,p[1]+n[1]*eps]),b=findSpaceAt(level,[p[0]-n[0]*eps,p[1]-n[1]*eps]);if(a&&b&&a.id!==b.id)adj.push({id:`adj:${a.id}:${b.id}:${o.id}`,level:level.index,from:a.id,to:b.id,openingId:o.id,wallId:w.id,type:o.type==='door'?'door':'opening'});}
    level.spaceTopology={rooms:next.map(r=>({id:r.id,areaM2:r.areaM2,wallIds:r.boundaryWallIds,centroid:r.centroid,spaceType:r.spaceType})),wallEdges:ownership,adjacency:adj.filter(x=>x.level===level.index),intersections:arr.segs.filter(s=>s.t0>EPS||s.t1<1-EPS).map(s=>({wallId:s.wallId,segmentId:s.id,t0:s.t0,t1:s.t1}))};
    for(const s of level.stairs||[]){const p=s.position?[s.position[0],s.position[1]]:null;if(!p)continue;const from=level, to=building.levels.find(l=>l.index===s.toFloor);const a=findSpaceAt(from,p),b=to?findSpaceAt(to,p):null;if(a&&b)vertical.push({id:`vertical:${s.id}`,stairId:s.id,fromLevel:from.index,toLevel:to.index,fromSpace:a.id,toSpace:b.id,type:'stair'});}
  }
  building.phase23.spaceTopology.rooms=globalRooms;building.phase23.spaceTopology.adjacency=[...new Map(adj.map(x=>[x.id,x])).values()];building.phase23.spaceTopology.verticalLinks=vertical;building.phase23.spaceTopology.wallOwnership=globalRooms.flatMap(r=>r.wallIds.map(w=>({wallId:w,level:r.level,roomId:r.id})));building.phase23.spaceTopology.intersections=(building.levels||[]).flatMap(l=>l.spaceTopology?.intersections||[]).map(x=>({...x,level:(building.levels.find(l=>l.spaceTopology?.intersections?.includes(x))?.index)}));building.phase23.spaceTopology.operations++;building.phase23.spaceTopology.lastRegenerated=now();building.phase23.associative={updatedAt:now(),rooms:globalRooms.length,adjacencies:building.phase23.spaceTopology.adjacency.length,verticalLinks:vertical.length,ceilingBindings:globalRooms.length,slabBindings:globalRooms.length};return building;}
export function phase23AssociativeUpdate(building,reason='space-topology-change'){normalizePhase23(building);regenerateSpaces23(building);building.phase23.associative.reason=reason;building.phase23.associative.updatedAt=now();return building;}
export function phase23Manifest(building){normalizePhase23(building);return{schema:PHASE23_SCHEMA,project:{id:building.id,name:building.name},spaceTopology:clone(building.phase23.spaceTopology),associative:clone(building.phase23.associative||{}),notes:['Phase 23 derives spaces from a planar wall arrangement including intersections and shared partitions.','Circulation and vertical links are model-derived coordination data and require professional review.']};}
export function validatePhase23(building){normalizePhase23(building);const errors=[],warnings=[];for(const l of building.levels||[]){const rooms=l.rooms||[];for(const r of rooms){if(!r.polygon||r.polygon.length<3)errors.push(`Space ${r.id} has no closed polygon.`);if((r.areaM2||0)<0.75)warnings.push(`Space ${r.id} is smaller than 0.75 m².`);for(const w of r.boundaryWallIds||[])if(!(l.walls||[]).some(x=>x.id===w))errors.push(`Space ${r.id} references missing wall ${w}.`);}for(const a of l.spaceTopology?.adjacency||[])if(a.from===a.to)errors.push(`Invalid self-adjacency ${a.id}.`);for(const w of l.walls||[]){const owners=(l.spaceTopology?.wallEdges||[]).filter(x=>x.wallId===w.id).map(x=>x.roomId);if(owners.length>2)errors.push(`Wall ${w.id} bounds more than two spaces.`);if(owners.length===0)warnings.push(`Wall ${w.id} does not bound a detected space.`);}}for(const v of building.phase23.spaceTopology.verticalLinks||[]){if(v.fromLevel===v.toLevel)errors.push(`Vertical link ${v.id} does not cross levels.`);}if(!building.phase23.associative?.updatedAt)warnings.push('Phase 23 topology has not been regenerated.');return{valid:errors.length===0,errors,warnings};}
